-- CreateEnum
CREATE TYPE "AuditAction" AS ENUM ('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTERED', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_STATUS_TOGGLED', 'USER_PASSWORD_RESET', 'CATEGORY_CREATED', 'CATEGORY_UPDATED', 'CATEGORY_DELETED', 'PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_DELETED', 'STOCK_MOVEMENT_ADDED', 'VENDOR_CREATED', 'VENDOR_UPDATED', 'VENDOR_DELETED', 'VENDOR_PRODUCTS_MAPPED', 'VENDOR_PRODUCT_UNMAPPED', 'PURCHASE_CREATED', 'PURCHASE_UPDATED', 'PURCHASE_CONFIRMED', 'PURCHASE_CANCELLED', 'PURCHASE_PAYMENT_UPDATED', 'SALE_CREATED', 'SALE_UPDATED', 'SALE_CONFIRMED', 'SALE_CANCELLED', 'SALE_PAYMENT_UPDATED');

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" "AuditAction" NOT NULL,
    "entity" TEXT NOT NULL,
    "entityId" TEXT,
    "metadata" JSONB,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
